server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true # 返回eureka的是ip，而不是主机名
    ip-address: 127.0.0.1  # 设置返回的ip是啥
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

